### ISSUE TITLE
easeui目前在Swift下可以用cocoapods集成吗？

### ISSUE THREAD

**Issue by stormluke** [easemob/easeui-ios-cocoapods#2]
用Swift试了下似乎不成功，有没有具体步骤？

**Comment by lizilong1989** [comment]
具体报什么错误

**Comment by johnchen** [comment]
Resolving dependencies of `Podfile`
[!] Unable to satisfy the following requirements:
- `MJRefresh (~> 3.0.6)` required by `EaseUI (1.0.0)`这是怎么回事直接pod的
